version: '3'

services:
  cas-server:
    environment:
      PORT: 80
      DATABASE_URL: postgresql://admin:aMTZsXCXMyoR7D2HXH@172.1.0.10:5432/wikipetiadev?schema=public
      JWT_SECRET: wolemachawolemachawolemacha
      FRONTEND_URL: http://localhost:3000
    networks:
      cas:
        ipv4_address: 172.1.0.2
    depends_on:
      - database
    build:
      context: ./
      dockerfile: ./dockerfile
    image: 'cas-server'
    ports:
      - '8080:80'
  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: wikipetiadev
      POSTGRES_PASSWORD: aMTZsXCXMyoR7D2HXH
      POSTGRES_USER: admin
    ports:
      - '5432:5432'
    volumes:
      - ./pg/data:/var/lib/postgresql/data
    networks:
      cas:
        ipv4_address: 172.1.0.10
networks:
  cas:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/24
