version: '3'

services:
  cas-server:
    environment:
      PORT: 80
    env_file:
      - docker.env
    networks:
      cas:
        ipv4_address: 172.1.0.2
    depends_on:
      - database
    build:
      context: ./
      dockerfile: ./dockerfile
    image: 'cas-server'
    ports:
      - '8080:80'
      - '5555:5555'
  database:
    image: 'postgres:latest'
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    volumes:
      - ./pg/data:/var/lib/postgresql/data
    networks:
      cas:
        ipv4_address: 172.1.0.10
networks:
  cas:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/24
